/**
 * Type definitions for Pending Response (Moderator Review Queue)
 *
 * These types represent responses awaiting moderator approval after
 * being generated by the RAG system with confidence below auto-send threshold.
 */

export interface Source {
  title: string;
  url: string;
}

export interface PendingResponse {
  id: string;
  question: string;
  answer: string;
  confidence: number; // 0.0 to 1.0
  detected_version: 'Bisq 1' | 'Bisq 2' | 'General';
  sources: Source[];
  created_at: string; // ISO 8601 timestamp
}

export interface PendingResponseWithOptimisticState extends PendingResponse {
  isRemoving?: boolean; // For optimistic UI updates
}
