import zipfile
from pathlib import Path

from app.core.config import Settings
from app.services.knowledge_updates.llm_wiki_review_importer import (
    ReviewedLLMWikiBatchImporter,
)
from app.services.knowledge_updates.llm_wiki_update_service import (
    KnowledgeUpdateService,
)
from app.services.rag.llm_wiki_loader import LLMWikiLoader
from app.services.training.unified_repository import UnifiedFAQCandidate


def _write_original_page(root: Path, *, body: str | None = None) -> Path:
    pages_dir = root / "knowledge" / "llm_wiki" / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)
    page = pages_dir / "bisq-easy-payments.md"
    page.write_text(
        body or """---
id: bisq-easy-payments
title: Bisq Easy payments
type: llm_wiki
page_type: support_playbook
status: proposed
protocol: bisq_easy
reviewed_by: null
reviewed_at: null
risk_level: medium
source_refs:
  - wiki:Bisq Easy
---
## Canonical Support Answer

Generated answer says to check the payment tablooks and maybe retry.

## Applies When

- The user asks about Bisq Easy payments.

## Do Not Say

- Do not promise support can reverse a payment.

## Evidence / Sources

- `wiki:Bisq Easy`

## Review Notes

Generated by the initial batch.

## Last Change Summary

Initial generated draft.
""",
        encoding="utf-8",
    )
    return page


def _write_reviewed_page(root: Path) -> Path:
    page = root / "bisq-easy-payments.md"
    page.write_text(
        """---
id: bisq-easy-payments
title: Bisq Easy payments
type: llm_wiki
page_type: support_playbook
status: proposed
protocol: bisq_easy
reviewed_by: null
reviewed_at: null
risk_level: medium
source_refs:
  - wiki:Bisq Easy
---
## Canonical Support Answer

Ask the user which Bisq Easy payment screen they mean and guide them to the trade details screen. If the payment has been marked as sent for 24 hours, ask them to share the exact status text before suggesting next steps.

## Applies When

- The user asks about Bisq Easy payments.
- The user mentions an unclear payment status.

## Do Not Say

- Do not promise support can reverse a payment.
- Do not tell users to edit files in `%USERPROFILE%\\Bisq2` unless the step is sourced.

## Evidence / Sources

- `wiki:Bisq Easy`

## Review Notes

Generated by the initial batch.

## Last Change Summary

Human clarified the support flow and Ficed wrong tab wording.
""",
        encoding="utf-8",
    )
    return page


def _candidate(**overrides) -> UnifiedFAQCandidate:
    values = {
        "id": 11,
        "source": "matrix",
        "source_event_id": "$event",
        "source_timestamp": "2026-05-13T10:00:00+00:00",
        "question_text": "Where can I see the Bisq Easy payment status?",
        "staff_answer": "Check the Bisq Easy trade details payment status.",
        "generated_answer": None,
        "staff_sender": "support",
        "embedding_similarity": None,
        "factual_alignment": None,
        "contradiction_score": 0.05,
        "completeness": None,
        "hallucination_risk": 0.1,
        "final_score": None,
        "llm_reasoning": None,
        "routing": "FULL_REVIEW",
        "review_status": "pending",
        "reviewed_by": None,
        "reviewed_at": None,
        "rejection_reason": None,
        "faq_id": None,
        "is_calibration_sample": True,
        "created_at": "2026-05-13T10:01:00+00:00",
        "updated_at": None,
        "protocol": "bisq_easy",
        "edited_staff_answer": None,
        "edited_question_text": None,
        "category": "payments",
        "generated_answer_sources": '[{"type":"wiki","title":"Bisq Easy"}]',
        "original_user_question": None,
        "original_staff_answer": None,
        "generation_confidence": 0.82,
        "has_correction": False,
    }
    values.update(overrides)
    return UnifiedFAQCandidate(**values)


def test_importer_mines_diff_feedback_and_normalizes_reviewed_pages(
    tmp_path: Path,
) -> None:
    original_page = _write_original_page(tmp_path)
    reviewed_dir = tmp_path / "reviewed"
    reviewed_dir.mkdir()
    _write_reviewed_page(reviewed_dir)

    service = KnowledgeUpdateService(
        settings=Settings(DATA_DIR=str(tmp_path)),
        db_path=str(tmp_path / "unified_training.db"),
    )
    importer = ReviewedLLMWikiBatchImporter(
        original_pages_dir=original_page.parent,
        knowledge_update_service=service,
    )

    result = importer.import_batch(
        reviewed_path=reviewed_dir,
        reviewer="suddenwhipvapor",
        reviewed_at="2026-06-27",
    )

    assert result.matched_count == 1
    assert result.loader_document_count == 1
    assert result.admin_section_leakage == []
    assert result.missing_originals == []

    page_result = result.pages[0]
    assert page_result.page_id == "bisq-easy-payments"
    assert page_result.changed_sections == [
        "Canonical Support Answer",
        "Applies When",
        "Do Not Say",
        "Last Change Summary",
    ]
    assert page_result.feedback_tags == [
        "factual_correction",
        "scope_narrowing",
        "missing_caveat",
        "source_support",
        "tone_wording",
    ]
    assert page_result.issues == [
        "metadata_not_reviewed",
        "copy_edit_needed",
        "source_coverage_needed",
    ]
    assert "status: reviewed" in page_result.normalized_markdown
    assert "reviewed_by: suddenwhipvapor" in page_result.normalized_markdown
    assert "reviewed_at: '2026-06-27'" in page_result.normalized_markdown
    assert "Review Notes" in page_result.normalized_markdown
    assert "Last Change Summary" in page_result.normalized_markdown

    records = service.list_generator_feedback_records(
        target_page_id=page_result.page_id
    )
    assert len(records) == 1
    assert records[0]["review_source"] == "batch_import"
    assert records[0]["candidate_id"] is None
    assert records[0]["target_page_id"] == "bisq-easy-payments"
    assert records[0]["feedback_tags"] == page_result.feedback_tags
    assert records[0]["future_generator_note"] == page_result.future_generator_note


def test_importer_can_apply_zip_batch_and_loader_excludes_admin_sections(
    tmp_path: Path,
) -> None:
    _write_original_page(tmp_path)
    reviewed_dir = tmp_path / "reviewed"
    reviewed_dir.mkdir()
    reviewed_page = _write_reviewed_page(reviewed_dir)
    zip_path = tmp_path / "reviewed.zip"
    with zipfile.ZipFile(zip_path, "w") as archive:
        archive.write(reviewed_page, arcname=reviewed_page.name)

    output_dir = tmp_path / "normalized"
    importer = ReviewedLLMWikiBatchImporter(
        original_pages_dir=tmp_path / "knowledge" / "llm_wiki" / "pages",
    )

    result = importer.import_batch(
        reviewed_path=zip_path,
        reviewer="suddenwhipvapor",
        reviewed_at="2026-06-27",
        output_dir=output_dir,
        apply=True,
    )

    written = output_dir / "bisq-easy-payments.md"
    assert result.matched_count == 1
    assert written.exists()
    assert "status: reviewed" in written.read_text(encoding="utf-8")

    documents = LLMWikiLoader().load_documents(output_dir)
    assert len(documents) == 1
    assert "Human clarified" not in documents[0].page_content
    assert "Generated by the initial batch" not in documents[0].page_content
    assert "trade details screen" in documents[0].page_content


def test_imported_batch_feedback_is_used_for_future_generation(
    tmp_path: Path,
) -> None:
    original_page = _write_original_page(tmp_path)
    reviewed_dir = tmp_path / "reviewed"
    reviewed_dir.mkdir()
    _write_reviewed_page(reviewed_dir)
    service = KnowledgeUpdateService(
        settings=Settings(DATA_DIR=str(tmp_path)),
        db_path=str(tmp_path / "unified_training.db"),
    )
    importer = ReviewedLLMWikiBatchImporter(
        original_pages_dir=original_page.parent,
        knowledge_update_service=service,
    )
    importer.import_batch(
        reviewed_path=reviewed_dir,
        reviewer="suddenwhipvapor",
        reviewed_at="2026-06-27",
    )

    proposal = service.get_or_create_proposal(candidate=_candidate())

    assert proposal.generator_feedback["example_count"] == 1
    assert "factual_correction" in proposal.generator_feedback["feedback_tags"]
    assert "source_support" in proposal.generator_feedback["feedback_tags"]
    assert any(
        "Human reviewer changed Canonical Support Answer" in note
        for note in proposal.generator_feedback["notes"]
    )
    assert any(
        op["id"] == "generator-feedback"
        and "Prior review feedback for this topic" in op["content"]
        for op in proposal.operations
    )


def test_importer_reports_reviewed_pages_without_generated_original(
    tmp_path: Path,
) -> None:
    reviewed_dir = tmp_path / "reviewed"
    reviewed_dir.mkdir()
    _write_reviewed_page(reviewed_dir)

    importer = ReviewedLLMWikiBatchImporter(original_pages_dir=tmp_path / "missing")

    result = importer.import_batch(
        reviewed_path=reviewed_dir,
        reviewer="suddenwhipvapor",
        reviewed_at="2026-06-27",
    )

    assert result.matched_count == 0
    assert result.pages == []
    assert result.missing_originals == ["bisq-easy-payments.md"]
