services:
  nginx:
    environment:
      - NGINX_TLS_CERTIFICATE=/etc/nginx/tls/${NGINX_TLS_CERTIFICATE_FILENAME:?Set NGINX_TLS_CERTIFICATE_FILENAME}
      - NGINX_TLS_PRIVATE_KEY=/etc/nginx/tls/${NGINX_TLS_PRIVATE_KEY_FILENAME:?Set NGINX_TLS_PRIVATE_KEY_FILENAME}
      - NGINX_TLS_REDIRECT_HTTP=${NGINX_TLS_REDIRECT_HTTP:-false}
    volumes:
      - "${NGINX_TLS_CERTIFICATE_DIR:?Set NGINX_TLS_CERTIFICATE_DIR}:/etc/nginx/tls:ro"
    ports:
      - "${NGINX_HTTPS_BIND_ADDRESS:?Set NGINX_HTTPS_BIND_ADDRESS}:443:443"
