services:
  bisq-api:
    image: your_dockerhub_username/bisq-api:latest  # pre-built production image
    restart: always
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
      # - BISQ_API_URL=http://host.docker.internal:8090  # For macOS/Windows
      - BISQ_API_URL=http://172.17.0.1:8090  # For Linux
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nextjs:
    image: your_dockerhub_username/nextjs:latest
    restart: always
    ports:
      - "3000:3000"

  vector-store:
    image: your_dockerhub_username/vector-store:latest
    restart: always
    volumes:
      - vector_data:/data

  reverse-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - bisq-api
      - nextjs

volumes:
  vector_data:
    driver: local
  api-data:
  bisq-data:
  prometheus-data:
  grafana-data:

networks:
  bisq-support-network:
    driver: bridge 